name: Build

on:
  push:
    branches:
      - main
  tags:
    - 'v*'

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Checkout sources
        uses: https://git.jackz.me/actions/checkout@v6
      - name: Setup Java
        uses: https://git.jackz.me/actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: https://git.jackz.me/actions/gradle-actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: https://git.jackz.me/actions/upload-artifact@v4
        with:
          name: build
          path: build/libs
  release:
    # Only release on tags
    if: startsWith(forgejo.ref, 'refs/tags/v')
    runs-on: debian-latest
    needs: build
    steps:
      - name: Pull artifact
        uses: https://git.jackz.me/actions/download-artifact@v4
        with:
          name: build
          merge-multiple: true
      - name: Create release
        uses: https://git.jackz.me/actions/forgejo-release@v2.7.3
        with:
          direction: upload
          release-dir: .
          prerelease: true
          override: true